project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: test.qmd

format:
  html:
    toc: true

  # (other formats)
  # pdf: default

execute:
  freeze: false



